# Override the app configuration for development. We want the code to
# be in a volume so it updates as we go and we want higher log
# level. Also, we don't want containers to restart automatically, if
# they fail, they fail.
version: "3.2"
services:
  cub_sign_in_app:
    restart: "no"
    build: ./app
    ports:
      - "8000:8000"
    command: >
      gunicorn --workers 1
          --bind :8000
          --log-level debug
          --access-logfile -
          app:app
    env_file:
      - ./app/.dev.env
    environment:
      - CUB_SIGN_IN_CONFIG=.dev.env
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1

  celery:
    restart: "no"
    build: ./app
    command: >
      celery worker
          --loglevel=DEBUG
          --app app.celery
    env_file: ./app/.dev.env
    environment:
      - CUB_SIGN_IN_CONFIG=.dev.env
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
