version: "3.2"

services:
  cub_sign_in_app:
    restart: always
    build: ./app
    ports:
      - "8000:8000"
    command: >
      gunicorn
          --workers 1
          --access-logfile -
          --log-level debug
          --bind :8000
          app:app
    env_file: ./app/.env
    environment:
      - CUB_SIGN_IN_CONFIG=.env
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    links:
      - redis
      - celery
    networks:
      - proxy
    volumes:
      - datavolume:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=flask"
      - "traefik.frontend.rule=${TRAEFIK_FRONTEND_RULE}"
      - "traefik.domain=${TRAEFIK_DOMAIN}"

  redis:
    restart: always
    image: "redis"
    ports:
      - "6379:6379"

  celery:
    restart: always
    build: ./app
    command: >
      celery worker
          --loglevel=DEBUG
          --app app.celery
    env_file: ./app/.env
    environment:
      - CUB_SIGN_IN_CONFIG=.env
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    links:
      - redis
    volumes:
      - datavolume:/data

  traefik:
    image: traefik:1.7.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - proxy


volumes:
  datavolume:

networks:
  proxy:
    external: true
