version: "3.2"

services:
  cub_sign_in_app:
    restart: always
    build: ./app
    ports:
      - "8000:8000"
    command: >
      gunicorn
          --workers 1
          --access-logfile -
          --log-level warn
          --bind :8000
          app:app
    env_file: ./app/.env
    environment:
      - CUB_SIGN_IN_CONFIG=.env
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    links:
      - redis
      - celery
    volumes:
      - datavolume:/data

  redis:
    restart: always
    image: "redis"
    # command: "redis-server"
    ports:
      - "6379:6379"

  celery:
    restart: always
    build: ./app
    # user: nobody
    command: >
      celery worker
          --loglevel=WARN
          --app app.celery
    env_file: ./app/.env
    environment:
      - CUB_SIGN_IN_CONFIG=.env
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    links:
      - redis
    volumes:
      - datavolume:/data

  nginx:
    image: "nginx:1.15.6"
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - cub_sign_in_app


volumes:
  datavolume: {}
