logLevel = "DEBUG"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "nicholas.spain96@gmail.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
# Defaults to prod ACME server
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0

  [[acme.domains]]
  main = "nspain.me"
  sans = ["cubs.nspain.me"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "cubs.nspain.me"
exposedbydefault = false
