logLevel = "INFO"
defaultEntryPoints = ["https"]

[file]
watch = true

[api]
address = ":8080"

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "nicholas.spain96@gmail.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0

  [[acme.domains]]
  main = "*.nspain.me"
  sans = ["nspain.me"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "nspain.me"
watch = true
exposedbydefault = false
